name: Upload Artifact CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Prepare a unique name for Artifacts
      run: |
        version=$(cat manifest.json | grep \"version\": | sed -e 's/[ ,\t:\/\\"<>|*?]/-/g' -e 's/--*/-/g')
        branch=$(echo -n "${GITHUB_REF#refs/heads/}" | sed -e 's/[ \t:\/\\"<>|*?]/-/g' -e 's/--*/-/g')
        echo "VERSION=$version" >> $GITHUB_ENV
        echo "BRANCH=$branch" >> $GITHUB_ENV

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install web-ext
      run: npm install --global web-ext

    - name: Archive extension
      run: web-ext build --ignore-files README.md

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        name: pr-not-approved${{ env.VERSION }}${{ env.BRANCH }}
        path: ./web-ext-artifacts/pr-not-approved-*.zip
